version: "3"


services:
  serrver:
    depends_on: 
      - db
    container_name: server
    init: true                    # run init scripts to kill zombie processes
    restart: unless-stopped
    build:
      context: ./server/.         # context for dockerfile
      dockerfile: Dockerfile      # use custom dockerfile
      args:                       # pass arguments to dockerfile
        - name=value
    ports:                        # map port 8080 on host to port 8080 on container "host:container"
      - 8080:8080
    networks:
      - db_net
      - client_net

  client:
    depends_on: 
      - serrver
    container_name: client
    init: true
    restart: unless-stopped
    build:
      context: ./client/.
      dockerfile: Dockerfile
      args:
        - name=value
    networks:
      - db_net

  db:
    container_name: db
    init: true
    restart: unless-stopped
    image: postgres:latest
    networks:
      - db_net
    
networks:
  db_net:
    driver: bridge
  client_net:
    driver: bridge