version: "3"

networks:
  db_net:
    driver: bridge
  client_net:
    driver: bridge

services:

  server:
    depends_on:
      - db
    container_name: server
    init: true                    # run init scripts to kill zombie processes
    restart: unless-stopped
    build:
      context: ./server/.         # context for dockerfile
      dockerfile: Dockerfile      # use custom dockerfile
      args:                       # pass arguments to dockerfile
        - name=value
    env_file:
      - .env
    ports:                        # map port 8080 on host to port 8080 on container "host:container"
      - 8080:8080
    volumes:
      - ./server/.:/app/          # only for dev, remove before final push
    networks:
      - db_net
      - client_net

  # client:
  #   depends_on: 
  #     - server
  #   container_name: client
  #   init: true
  #   restart: unless-stopped
  #   build:
  #     context: ./client/.
  #     dockerfile: Dockerfile
  #     args:
  #       - name=value
  #   networks:
  #     - db_net

  db:
    container_name: db
    init: true
    restart: unless-stopped
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - db_net
