version: "3"

networks:
  db_net:
    driver: bridge

services:

  backend:
    depends_on:
      - db
    container_name: backend
    init: true                    # run init scripts to kill zombie processes
    restart: unless-stopped
    env_file:
      - .env                      # pass environment variables to container
    build:
      context: ./backend/.         # context for dockerfile build (building can't copy files outside of context)
      dockerfile: Dockerfile      # use custom dockerfile
      args:                       # pass arguments to dockerfile
        - name=value
    ports:                        # map port 8080 on host to port 8080 on container "host:container"
      - 8080:8080
    volumes:                      # !!!!!!!!!!!!!!!!!!!  only for dev, remove for production
      - ./backend/.:/app/          # use to update containers files which have been copied from local directory ./server/
    networks:
      - db_net

  frontend:
    depends_on: 
      - backend
    container_name: frontend
    init: true
    restart: unless-stopped
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    ports:
      - 8585:8585
    environment:
      PORT: ${CLIENT_PORT}                # Change default port of React (3000 by default)
      REACT_APP_SERVER_PORT: ${SERVER_PORT}
      REACT_APP_CLIENT_PORT: ${CLIENT_PORT}
      REACT_APP_SERVER_HOST: ${SERVER_HOST}
    volumes:
      - ./frontend/.:/app/
  
  db:
    container_name: db
    init: true
    restart: unless-stopped
    image: postgres:latest
    ports:
      - 5432:5432                        # map port 5432 on host to port 5432 on container "host:container" Inaccessible from DBeaver if not mapped
    environment:                         # pass environnement variables to container
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - db_net
